# Generated by Django 5.0.7 on 2026-07-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this account was first connected"
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="engagement_rate",
            field=models.FloatField(
                default=0, help_text="Average engagement rate as a percentage"
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="followers",
            field=models.IntegerField(
                default=0, help_text="Total follower / subscriber count"
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="growth_percentage",
            field=models.FloatField(
                default=0, help_text="Month-over-month growth percentage"
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("youtube", "YouTube"),
                    ("twitter", "Twitter/X"),
                ],
                help_text="Social media platform identifier",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="total_posts",
            field=models.IntegerField(
                default=0, help_text="Total published posts / videos"
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="user",
            field=models.ForeignKey(
                help_text="Owner of this social account connection",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="username",
            field=models.CharField(
                help_text="Handle or display name on the platform", max_length=100
            ),
        ),
    ]
